sudo: required
language: generic
services:
  - docker  

before_install:
  - docker build -t ruyao2k/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ruyao2k/react-test npm test -- --coverage || true

after_success:
  - docker build -t ruyao2k/complex-client ./client
  - docker build -t ruyao2k/complex-nginx ./nginx
  - docker build -t ruyao2k/complex-server ./server
  - docker build -t ruyao2k/complex-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push ruyao2k/complex-client
  - docker push ruyao2k/complex-nginx
  - docker push ruyao2k/complex-server
  - docker push ruyao2k/complex-worker

 
